### ISSUE TITLE
[Enhancement] external config file

### ISSUE THREAD

**Issue by gigawatts** [cschladetsch/LogiNumPad#1]
How hard would it be to move the color assignments of each key out of the code and into an external config file? I'm thinking I'd just like it to toggle the NUM key color, and maybe black out number keys when num luck is off. It would be awesome to do the same thing with the Caps Lock and Scroll Lock key LEDs as well.

FYI, I just found this program and it works great on my G513 (after I installed G Hub, that is, it wouldn't work with just LGS), I'd just like to be able to easily tweak it a bit without installing a C# compiler.

**Comment by cschladetsch** [comment]
Seems reasonable, I'll do it tonight.

**Comment by cschladetsch** [comment]
Colors now stored in `App.Config` file. Should be self-explanatory. 

Have not resolved CapsLock or ScrollLock keys; please open separate issues for those.

**Comment by cschladetsch** [comment]
CapsLock is tricky for me to resolve because I use https://github.com/cschladetsch/InCode which remaps `CapsLock` key so breaks my flow.

**Comment by gigawatts** [comment]
Yes, that's perfect! I just set it up so the NUM key is red and all the numbers go black when numlock is off, and light the NUM key and numbers up green when numlock is on.

Thank you!
