### ISSUE TITLE
Windows Service / Scroll Lock

### ISSUE THREAD

**Issue by SB192** [cschladetsch/LogiNumPad#4]
Really appreciate the Application due to the lack of the native indicator for my Keyboard. I would be glad if it would be a windows service however. Also would it be possible to add scroll lock indicator?

**Comment by cschladetsch** [comment]
You can change the key on line 113 of Program.cs to be VK_SCROLLOCK or whatever key you want.

I don't have time to make it a Service; though it would be a nice to have for sure!

**Comment by SB192** [comment]
Thanks for the fast response! Yes the service would be great but I can sure live without it. Regarding the scroll lock; I would like to inticate the scroll lock state itself since the indicator light is also missing on the keyboard.

This is actually my first excourse into programming. However I think I was able to understand most of your program and tried to adjust your program to either do both or make a second version operating in the same way but just for the scroll lock. As I understand it you are checking for the num lock state in line 20. How would I be able to do the same for the scroll lock.

Sorry for this rookie question and request.

**Comment by SB192** [comment]
Adjusted 0x90 to 0x91 in Line 20 and arragend everything else so it fits to the scroll lock. Works fine for me now. Thanks again for the application.
